development:
  access_key_id: AKIAJVNGWQGBR2HCQ45Q
  secret_access_key: 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
  bucket: poopsquare_dev
  
test:
  access_key_id: AKIAJVNGWQGBR2HCQ45Q
  secret_access_key: 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
  bucket: poopsquare_dev
